#!/bin/bash

NUMBER1=100
NUMBER2=200
NAME=DEEPTHI
RESULT=$(($NUMBER1+$NUMBER2+$NAME))
echo "Total is:$RESULT"
#size =4,max_index=3
LEADERS=("MODI" "PUTIN" "TRUMP" "LEE")
echo "ALL LEADERS:${LEADERS[@]}"
echo "FIRST LEADER:${LEADERS[0]}"
echo "TENTH LEADER:${LEADERS[10]}"
ECHO "hi"