#!/bin/bash

NUMBER1=100
NUMBER2=200
NAME=DEEPTHI
RESULT=$(($NUMBER1+$NUMBER2+$NAME))
echo "Total is:$RESULT"
LEADERS=(MODI,PUTIN,TRUMP,LEE)
echo "ALL LEADERS:${LEADERS[@]}"
echo "ALL LEADERS:${LEADERS[0]}"